version: '3.4'

services:
  bikerentalsystem.api:
    image: ${DOCKER_REGISTRY-}bikerentalsystemapi
    build:
      context: .
      dockerfile: src/BikeRentalSystem.Api/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

